name: Release

on:
  workflow_run:
    workflows: ['Build And Test']
    branches: [master, v1]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: github.event.workflow_run.ref_name
      - name: Install
        run: npm ci
      - name: Set project name
        run: echo "SEMANTIC_RELEASE_PACKAGE=$(jq -r '.name' package.json)" >> $GITHUB_ENV
      - name: Release
        run: npx semantic-release --dry-run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_SEMANTIC_RELEASE_WEBHOOK }}
      - name: Set npm registry to npm
        run: npm config set @avallone-io:registry https://registry.npmjs.org
      - name: Npm registry authentication
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: Release to NPM
        run: npm publish --dry-run --access public
